name: Issue Workflow

on:
  issues:
    types: [opened, edited, closed]

jobs:
  handle-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print issue information
      run: |
        echo "Issue number: ${{ github.event.issue.number }}"
        echo "Issue title: ${{ github.event.issue.title }}"
        echo "Issue state: ${{ github.event.issue.state }}"
        echo "Issue body: ${{ github.event.issue.body }}"

    - name: Comment on the issue
      if: github.event.action == 'opened'
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Thanks for opening this issue! We will look into it as soon as possible.

