name: Conditional Steps Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Always run this step
      run: echo "This step always runs"

    - name: Run this step on main branch
      if: github.ref == 'refs/heads/master'
      run: echo "This step runs only on the master branch"

    - name: Run this step if a file has changed
      if: contains(github.event.head_commit.message, 'Update README.md')
      run: echo "This step runs if the commit message contains 'Update README.md'"

    - name: Run this step if previous step succeeded
      if: success()
      run: echo "This step runs if all previous steps succeeded"

    - name: Run this step if previous step failed
      if: failure()
      run: echo "This step runs if the previous step failed"

