    name: CI

    on: [push]

    env:
      GLOBAL_VAR: "This is a global variable"

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Run a one-line script
          run: "Hello"
        - name: Print global variable
          run: echo $GLOBAL_VAR
