name: Multi-Job Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Job 1 script
      run: echo "Running Job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Job 2 script
      run: echo "Running Job 2"

  job3:
    runs-on: ubuntu-latest
    needs: job1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Job 3 script
      run: echo "Running Job 3"

