    name: CI

    on: [push]

    env:
      GLOBAL_VAR: "This is a global variable"

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Run script
          run: ./script.sh
